### ISSUE TITLE
Indicate whether the app was launched at login

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/LaunchAtLogin-Legacy#33]
Sometimes you would want different behavior if the app was launched at login vs. normally. For example, you want a window to show when launched normally, but not when launched at login.

We could add a property `LaunchAtLogin.wasLaunchedAtLogin` for this.

The helper app will have to somehow pass a message to the main app, which we'll read and use in the `.wasLaunchedAtLogin` property.

One possible solution here: https://blog.timschroeder.net/2014/01/25/detecting-launch-at-login-revisited/ But I was hoping for a simpler solution.

---

I have tried checking `keySenderPIDAttr` at `applicationDidFinishLaunching`, but it just pointed at the main app.

**Comment by cbjeukendrup** [comment]
Another solution could be to launch the main app with a command line flag (for example "LaunchedAtLogin", so that it can look if it was launched with that flag. It would be great if the name of that flag is customizable.

**Comment by sindresorhus** [comment]
@cbjeukendrup That's the obvious solution, yes, but unfortunately doesn't work with sandboxing:

> If the calling process is sandboxed, the system ignores the value of this property. - https://developer.apple.com/documentation/appkit/nsworkspace/openconfiguration/3172708-arguments

**Comment by cbjeukendrup** [comment]
Ah, sorry, missed that one. That makes it a lot more complicated...

**Comment by gpoitch** [comment]
I was able to do this by creating an App Group and in the launcher set:
```swift
UserDefaults(suiteName: "[TeamId][AppGroupId]")?.set(true, forKey: "didLaunchAtLogin")
```
Then in the main app, read that value then clear it.

It might not be feasible for a drop in library like this to set that up, but at least it's a simple solution.

**Comment by sindresorhus** [comment]
@gpoitch That's a good workaround. Thanks for sharing. However, I don't want to require App Group for LaunchAtLogin users, so I think the more complicated solution is a better fit for LaunchAtLogin.

**Comment by mkathuri** [comment]
I took the approach opposite to that of @sindresorhus by having the main app asking the helper app to terminate. IMO, this approach ensures that both the main and helper app are initialized properly and only then, can exchange messages.

I used the simple `DistributedNotificationCenter` mechanism, which seems to work well for my case so far. Here's my code:

In `LaunchAtLogin` enum:
```swift
// Requires AppKit to be imported
public static let wasLaunchedOnLogin: Bool = {
        let bundleIdentifier = Bundle.main.bundleIdentifier!
        let mainBundleIdentifier = "\(bundleIdentifier)-LaunchAtLoginHelper"
        // If helper is not running
        if NSRunningApplication.runningApplications(withBundleIdentifier: mainBundleIdentifier).isEmpty {
            return false
        } else {
            // Helper is running, ask it to terminate
            let nc = DistributedNotificationCenter.default()
            nc.post(name: NSNotification.Name("TerminateHelper"), object: nil)
            return true
        }
}()
```

`AppDelegate` class in `LaunchAtLoginHelper`:
```swift
final class AppDelegate: NSObject, NSApplicationDelegate {
	let nc = DistributedNotificationCenter.default()
	
	@objc func terminateApp() {
		NSLog("LaunchAtLogin helper terminateApp called")
		nc.removeObserver(self)
		NSApp.terminate(nil)
	}
	
	func applicationDidFinishLaunching(_ notification: Notification) {
		let bundleIdentifier = Bundle.main.bundleIdentifier!
		let mainBundleIdentifier = bundleIdentifier.replacingOccurrences(of: #"-LaunchAtLoginHelper$"#, with: "", options: .regularExpression)

		// Ensures the app is not already running.
		guard NSRunningApplication.runningApplications(withBundleIdentifier: mainBundleIdentifier).isEmpty else {
			NSApp.terminate(nil)
			return
		}

		let pathComponents = (Bundle.main.bundlePath as NSString).pathComponents
		let mainPath = NSString.path(withComponents: Array(pathComponents[0...(pathComponents.count - 5)]))
		NSWorkspace.shared.launchApplication(mainPath)
		nc.addObserver(self, selector: #selector(terminateApp), name: NSNotification.Name("TerminateHelper"), object: nil)
		NSLog("LaunchAtLogin helper exited")
	}
}
```

This seems to work on my sandboxed app running on my developer MacBook Pro. Any feedback is appreciated.

**Comment by sindresorhus** [comment]
The tricks mentioned in this thread will no longer work with the new API for launch at login in macOS 13: https://developer.apple.com/documentation/servicemanagement/smappservice/3945412-mainapp?changes=latest_minor

So we need some other ideas.

Please also submit feedback to Apple (using the Feedback Assistant app) that there needs to be an API for this. Like I have done in: https://github.com/feedback-assistant/reports/issues/337

**Comment by technusm1** [comment]
@sindresorhus I agree that a helper app is no longer required and with new API, one could simply register mainAppService to be launched at login, but I think it would still be necessary for this use case, as the API doesn't provide any way to differentiate between automatic login launch and manual launches.

To that end, I've explored Apple's documentation on sandboxed applications and came across this peculiar bit on this [link](https://developer.apple.com/library/archive/documentation/Security/Conceptual/AppSandboxDesignGuide/DesigningYourSandbox/DesigningYourSandbox.html):
> With App Sandbox, you can receive Apple events and respond to Apple events, but you cannot send Apple events to arbitrary apps.

I found an answer on StackOverflow related to Apple events: https://stackoverflow.com/a/19890943/4385319

And here's what I've tried so far:
In my AppDelegate, I added the following code:
```swift
func applicationWillFinishLaunching(_ notification: Notification) {
        NSAppleEventManager.shared().setEventHandler(self, andSelector: #selector(AppDelegate.handleEvent(_:withReplyEvent:)), forEventClass: AEEventClass(kCoreEventClass), andEventID: AEEventID(kAEOpenApplication))
}
```
Now my trouble begins:
```swift
@objc func handleEvent(_ event: NSAppleEventDescriptor!, withReplyEvent: NSAppleEventDescriptor!) {
    // I'm trying to compare the following two things (as per the answer found on StackOverflow):
    // event?.paramDescriptor(forKeyword: keyAEPropData)?.enumCodeValue
    // keyAELaunchedAsLogInItem
}
```
So far, the expression `event?.paramDescriptor(forKeyword: keyAEPropData)?.enumCodeValue` returns nil when my app is launched at login (using LaunchAtLogin framework on macOS 12) and is non-nil optional value otherwise (when I manually open it).

To those who have deeper knowledge on this topic, here's my question: ***Is checking the above expression for nil and non-nil a reliable way to say that my app was launched at login or not?***

Apologies if I missed something

**Comment by krishsatya** [comment]
I see this thread has gone quiet but I'll add a not-so-great option to the mix. Perhaps we could use the `time since last login` as a proxy for whether the app was launched at login or not. It is by no means perfect, however, if the OS doesn't emit an event when an app is started at login, what reliable options are available?

**Comment by longseespace** [comment]
I tried this one and it seems to work: https://hisaac.net/how-to-detect-if-your-macos-app-was-launched-as-a-login-item/

**Comment by krishsatya** [comment]
I was able to implement the solution linked to by @longseespace. Link has changed though: https://hisaac.net/blog/how-to-detect-if-your-macos-app-was-launched-as-a-login-item/.

**Comment by ShlomoCode** [comment]
@krishsatya @longseespace Which macOS did it work for you?
In macOS 14 using `SMAppService` it seems that `NSAppleEventManager.shared().currentAppleEvent` is `nil`

**Comment by ShlomoCode** [comment]
OK, i got it. it must be in `applicationDidFinishLaunching`

**Comment by sindresorhus** [comment]
It's available in the modern version of this package. I don't plan to add it here.

https://github.com/sindresorhus/LaunchAtLogin-Modern/blob/a04ec1c363be3627734f6dad757d82f5d4fa8fcc/Sources/LaunchAtLogin/LaunchAtLogin.swift#L34-L44
